import type { ConnectorId } from '../../domain/connector/identity.js';
import { validateToolManifest } from '../../domain/connector/manifest-validation.js';
import type { VerifiedToolManifest } from '../../domain/connector/manifest-validation.js';
import { INFRASTRUCTURE_CONNECTOR_ID } from '../../domain/infrastructure/constants.js';

const CONNECTOR_ID = INFRASTRUCTURE_CONNECTOR_ID as ConnectorId;

const buildTool = (raw: Record<string, unknown>): VerifiedToolManifest => {
  const result = validateToolManifest(raw);
  if (!result.ok) throw new Error(result.error.reason);
  return result.value;
};

const serverIdProperty = { type: 'string', maxLength: 128 };
const serviceIdProperty = { type: 'string', maxLength: 128 };
const environmentIdProperty = { type: 'string', maxLength: 128 };
const releaseIdProperty = { type: 'string', maxLength: 128 };

export const INFRASTRUCTURE_TOOLS: readonly VerifiedToolManifest[] = Object.freeze([
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.servers.list',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'List Servers',
    description: 'List declared servers from inventory.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { environmentId: environmentIdProperty },
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { serverIds: { type: 'array', items: serverIdProperty, maxItems: 256 } },
      required: ['serverIds'],
    },
    capability: 'list',
    riskClass: 'low',
    sideEffectClass: 'READ_ONLY',
    approvalRequirement: 'policy',
    timeoutMs: 5_000,
    idempotencySupport: 'none',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.server.inspect',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Inspect Server',
    description: 'Inspect declared server metadata.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { serverId: serverIdProperty },
      required: ['serverId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        lifecycleStatus: { type: 'string', maxLength: 32 },
        displayName: { type: 'string', maxLength: 128 },
      },
      required: ['serverId', 'lifecycleStatus', 'displayName'],
    },
    capability: 'read',
    riskClass: 'low',
    sideEffectClass: 'READ_ONLY',
    approvalRequirement: 'policy',
    timeoutMs: 5_000,
    idempotencySupport: 'none',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.server.resources.read',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Read Server Resources',
    description: 'Read bounded server resource snapshot.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { serverId: serverIdProperty },
      required: ['serverId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        cpuUtilizationPercent: { type: 'number' },
        memoryUsedBytes: { type: 'integer' },
        memoryTotalBytes: { type: 'integer' },
      },
      required: ['serverId'],
    },
    capability: 'read',
    riskClass: 'low',
    sideEffectClass: 'READ_ONLY',
    approvalRequirement: 'policy',
    timeoutMs: 5_000,
    idempotencySupport: 'none',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.services.list',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'List Services',
    description: 'List declared services.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { serverId: serverIdProperty, environmentId: environmentIdProperty },
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { serviceIds: { type: 'array', items: serviceIdProperty, maxItems: 256 } },
      required: ['serviceIds'],
    },
    capability: 'list',
    riskClass: 'low',
    sideEffectClass: 'READ_ONLY',
    approvalRequirement: 'policy',
    timeoutMs: 5_000,
    idempotencySupport: 'none',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.service.status.read',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Read Service Status',
    description: 'Read bounded service status.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        serviceId: serviceIdProperty,
      },
      required: ['serverId', 'serviceId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        serviceId: serviceIdProperty,
        activeState: { type: 'string', maxLength: 16 },
      },
      required: ['serverId', 'serviceId', 'activeState'],
    },
    capability: 'read',
    riskClass: 'low',
    sideEffectClass: 'READ_ONLY',
    approvalRequirement: 'policy',
    timeoutMs: 5_000,
    idempotencySupport: 'none',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.service.logs.read',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Read Service Logs',
    description: 'Read bounded sanitized service logs.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        serviceId: serviceIdProperty,
        maximumLines: { type: 'integer', minimum: 1, maximum: 500 },
        maximumBytes: { type: 'integer', minimum: 1, maximum: 65536 },
      },
      required: ['serverId', 'serviceId', 'maximumLines', 'maximumBytes'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        lines: { type: 'array', items: { type: 'string', maxLength: 4096 }, maxItems: 500 },
        truncated: { type: 'boolean' },
        redactionCount: { type: 'integer' },
        controlCharacterReplacementCount: { type: 'integer' },
      },
      required: ['lines', 'truncated', 'redactionCount', 'controlCharacterReplacementCount'],
    },
    capability: 'read',
    riskClass: 'medium',
    sideEffectClass: 'READ_ONLY',
    approvalRequirement: 'policy',
    timeoutMs: 10_000,
    idempotencySupport: 'none',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'confidential',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.drift.inspect',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Inspect Drift',
    description: 'Compare declared and observed state without repair.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        serviceId: serviceIdProperty,
      },
      required: ['serverId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        driftKinds: { type: 'array', items: { type: 'string', maxLength: 64 }, maxItems: 16 },
      },
      required: ['driftKinds'],
    },
    capability: 'read',
    riskClass: 'low',
    sideEffectClass: 'READ_ONLY',
    approvalRequirement: 'policy',
    timeoutMs: 5_000,
    idempotencySupport: 'none',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.service.restart',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Restart Service',
    description: 'Restart a service after approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        serviceId: serviceIdProperty,
        environmentId: environmentIdProperty,
      },
      required: ['serverId', 'serviceId', 'environmentId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { restarted: { type: 'boolean' } },
      required: ['restarted'],
    },
    capability: 'restart',
    riskClass: 'high',
    sideEffectClass: 'INFRASTRUCTURE',
    approvalRequirement: 'always',
    timeoutMs: 30_000,
    idempotencySupport: 'keyed',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.release.deploy',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Deploy Release',
    description: 'Deploy an approved release after approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        serviceId: serviceIdProperty,
        environmentId: environmentIdProperty,
        releaseId: releaseIdProperty,
      },
      required: ['serverId', 'serviceId', 'environmentId', 'releaseId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { deployed: { type: 'boolean' }, releaseId: releaseIdProperty },
      required: ['deployed', 'releaseId'],
    },
    capability: 'deploy',
    riskClass: 'critical',
    sideEffectClass: 'INFRASTRUCTURE',
    approvalRequirement: 'always',
    timeoutMs: 120_000,
    idempotencySupport: 'keyed',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.release.rollback',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Rollback Release',
    description: 'Rollback an approved release after approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        serviceId: serviceIdProperty,
        environmentId: environmentIdProperty,
        releaseId: releaseIdProperty,
      },
      required: ['serverId', 'serviceId', 'environmentId', 'releaseId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { rolledBack: { type: 'boolean' }, releaseId: releaseIdProperty },
      required: ['rolledBack', 'releaseId'],
    },
    capability: 'deploy',
    riskClass: 'critical',
    sideEffectClass: 'INFRASTRUCTURE',
    approvalRequirement: 'always',
    timeoutMs: 120_000,
    idempotencySupport: 'keyed',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
  buildTool({
    schemaVersion: 'connector-tool/1',
    toolId: 'infrastructure.server.reboot',
    connectorId: CONNECTOR_ID,
    version: '1.0.0',
    title: 'Reboot Server',
    description: 'Reboot a server after approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        serverId: serverIdProperty,
        environmentId: environmentIdProperty,
        providerId: { type: 'string', maxLength: 128 },
      },
      required: ['serverId', 'environmentId', 'providerId'],
    },
    outputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: { rebooted: { type: 'boolean' } },
      required: ['rebooted'],
    },
    capability: 'administer',
    riskClass: 'critical',
    sideEffectClass: 'INFRASTRUCTURE',
    approvalRequirement: 'always',
    timeoutMs: 120_000,
    idempotencySupport: 'keyed',
    cancellationSupport: 'cooperative',
    dataSensitivity: 'internal',
    networkRequirement: 'none',
    accountRequirement: 'none',
  }),
]);

export const INFRASTRUCTURE_HARD_DENIED_MANIFEST_ATTEMPTS = Object.freeze([
  {
    toolId: 'infrastructure.server.delete',
    sideEffectClass: 'DESTRUCTIVE',
    capability: 'delete',
  },
  {
    toolId: 'infrastructure.firewall.change',
    sideEffectClass: 'CREDENTIAL_OR_SECURITY_CHANGE',
    capability: 'administer',
  },
  {
    toolId: 'infrastructure.credential.rotate',
    sideEffectClass: 'CREDENTIAL_OR_SECURITY_CHANGE',
    capability: 'administer',
  },
  {
    toolId: 'infrastructure.provider.purchase',
    sideEffectClass: 'FINANCIAL',
    capability: 'create',
  },
  {
    toolId: 'infrastructure.provider.plan.change',
    sideEffectClass: 'FINANCIAL',
    capability: 'create',
  },
] as const);
